---
version: 2.1

orbs:
  crystal: manastech/crystal@1.0

workflows:
  version: 2
  build:
    jobs:
      - crystal/test:
          pre-steps:
            - run: apt-get update && apt-get install -y libmagic-dev
          format-check: false
          name: test-on-locked-version
          executor:
            name: crystal/default
            tag: 1.6.0
      - collect-artifacts

jobs:
  collect-artifacts:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - run: |
          ls
          ./scripts/ci 
          cp tmp/capture_stderr.cr /root/test-results/crystal-spec/
