#!/usr/bin/env bash

cd_safe() {
  cd "$1" || echo "unable to cd to: $1" && exit 1
}

is_cmd() {
  command -v "$1" > /dev/null
}

if ! is_cmd git; then
  echo "git not found in PATH: $PATH"
  exit 2
fi

libmagic_repo="https://github.com/pablotron/libmagic-crystal.git"
this_path="$(git rev-parse --show-toplevel)"
lib_path="$this_path/lib"

mkdir "$lib_path"
git clone "$libmagic_repo" "$lib_path/libmagic-crystal"

echo "installing libmagic and crystal..."
if is_cmd brew; then
  brew install crystal-lang libmagic
else
  echo "enter password to install with apt or ctrl-c to do it yourself..."
  curl https://dist.crystal-lang.org/apt/setup.sh | sudo bash
  sudo apt-get install libmagic crystal
fi

echo "testing..."
"$this_path/scripts/test"
