#!/usr/bin/env bash

command_exists() { command -v "$1" > /dev/null 2>&1; }

if ! command_exists git; then
  echo "git not found in PATH: $PATH"
  exit 2
fi

this_path="$(git rev-parse --show-toplevel)"
lib_path="$this_path/lib"

mkdir "$lib_path"

echo "installing libmagic, crystal, zlib, bzip2..."
if command_exists brew; then
  brew install crystal-lang libmagic zlib bzip2

  echo "bootstrapping docker..."
  brew install virtualbox docker docker-machine
  brew services restart docker-machine
  docker-machine create --driver virtualbox default
  eval "$(docker-machine env default)"
  docker-machine regenerate-certs default
  docker-machine restart
  docker build .
else
  echo "enter password to install with apt or ctrl-c to do it yourself..."
  curl https://dist.crystal-lang.org/apt/setup.sh | sudo bash
  sudo apt-get install libmagic crystal libyaml-dev libxml2-dev libmagic-dev
fi

echo "installing shards..."
shards install

echo "testing..."
"$this_path/scripts/test"
