#!/usr/bin/env bash

command_exists() { command -v "$1" > /dev/null 2>&1; }

if ! command_exists git; then
  echo "git not found in PATH: $PATH"
  exit 2
fi

libmagic_repo="https://github.com/pablotron/libmagic-crystal.git"
this_path="$(git rev-parse --show-toplevel)"
lib_path="$this_path/lib"

mkdir "$lib_path"
git clone "$libmagic_repo" "$lib_path/libmagic-crystal"

echo "installing libmagic and crystal..."
if command_exists brew; then
  brew install crystal-lang libmagic
else
  echo "enter password to install with apt or ctrl-c to do it yourself..."
  curl https://dist.crystal-lang.org/apt/setup.sh | sudo bash
  sudo apt-get install libmagic crystal libyaml-dev libxml2-dev libmagic-dev
fi

echo "testing..."
"$this_path/scripts/test"
